name: Mostrar estructura del proyecto

on:
  push:
    branches: [ "master" ]

jobs:
  mostrar-estructura:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Mostrar estructura del proyecto
        run: |
          echo "📁 Estructura del proyecto:"
          ls -R
